### ISSUE TITLE
Undefined sqlite3 on Ubuntu 24.04

### ISSUE THREAD

**Issue by jefft0** [berty/berty#4871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

CLI tools (berty mini, daemon, etc.)

### Berty product version

Latest commit from PR https://github.com/berty/berty/pull/4870

### OS

Linux

### OS version

Ubuntu 24.04

### Device

Ubuntu virtual machine

### Steps to reproduce

1. Install Go 1.23.2
2. Clone Berty.
3. In berty/go, enter `make install`

### Current behavior

Prints this build error:
```
internal/messengerdb/db.go:178:49: undefined: sqlite3.ErrNo
internal/messengerdb/db.go:179:24: undefined: sqlite3.Error
internal/messengerdb/db.go:320:33: undefined: sqlite3.ErrConstraint
internal/messengerdb/db.go:430:52: undefined: sqlite3.ErrConstraint
```

### Expected behavior

Should build. It builds OK on Ubuntu 22.04.

**Comment by D4ryl00** [comment]
Do you have cgo enabled? To enable it, you should have a GCC compiler.

**Comment by jefft0** [comment]
> Do you have cgo enabled? To enable it, you should have a GCC compiler.

You're right. I installed `build-essential` and it works. I made a pull request to[ update INSTALL.md in weshnet](https://github.com/berty/weshnet/pull/102), which are the instructions that I follow to install prerequisites for berty.

**Comment by jefft0** [comment]
Close as resolved by https://github.com/berty/weshnet/pull/102 .
